name: Notify Release PR Events via Slack

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    # if: startsWith(github.head_ref, 'release') || startsWith(github.head_ref, 'hotfix')
    steps:
          
      - name: Get PR Contributor Emails
        id: get_contributors
        if: github.event.action == 'opened' || (github.event.action == 'closed' && github.event.pull_request.merged == true)
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const emails = new Set();
            for (const commit of commits) {
              if (commit.commit && commit.commit.author && commit.commit.author.email) {
                emails.add(commit.commit.author.email);
              }
            }
            const emailList = Array.from(emails).join(", ");
            core.info(`Contributor Emails: ${emailList}`);
            return emailList;
          result-encoding: string
